### ISSUE TITLE
VideoSdk blocks audio sound when initiated even after exit and dispose

### ISSUE THREAD

**Issue by Vadefolarin** [videosdk-live/videosdk-rtc-flutter-sdk-example#24]
I  am using videosdk with RingtonePlayer , The ringtone rings out initially, but when a call(audio/video) has been initiated and eventually dispose off, video sdk still blocks sounds both from  the ringtoneplayer and  other sound from the phone.
I would be happy if this is seen and attended to early.

**Comment by yash-chudasama** [comment]
Hey @Vadefolarin, thank you for mentioning this issue. We will work on this issue and get back to you soon. It might take some time as we have some other high priorities also.

Thank You !!

**Comment by arjun-kava** [comment]
Solved
