### ISSUE TITLE
Error while getting baseUrl

### ISSUE THREAD

**Issue by edpraise** [videosdk-live/videosdk-rtc-flutter-sdk-example#25]
hello guys 
please what could be the reason for this error?

"Error while getting baseUrl"

**Comment by yash-chudasama** [comment]
Hey @edpraise, can you please describe steps to reproduce the error ?

**Comment by adrianprawira** [comment]
I get this issue too, in my case it is because of the token that inputted in .env is invalid. Do you know which token that needed for creating meetingID? @yash-chudasama 
![image](https://user-images.githubusercontent.com/87126929/191893781-5103ad13-3bab-4e5d-b67d-4696c83728b4.png)

**Comment by rajansurani** [comment]
@adrianprawira How are ou generating te token? Are you using it from the dashboard or generating by your own?

**Comment by adrianprawira** [comment]
> @adrianprawira How are ou generating te token? Are you using it from the dashboard or generating by your own?

Greetings, it's already solved. turns out i need to use generated token from APIKeys Settings from web.
