### ISSUE TITLE
Flutter Web [QUESTION]

### ISSUE THREAD

**Issue by ihorkozar** [videosdk-live/videosdk-rtc-flutter-sdk-example#28]
I would like to inquire about flutter web support. At what stage is the implementation and is it possible to count on it in the near future?

**Comment by luvishq** [comment]
Any updates here?

**Comment by arjun-kava** [comment]
Hey, @luvishq and @ihorkozar We have launched Flutter Web as beta. Please follow this doc: https://docs.videosdk.live/flutter/guide/video-and-audio-calling-api-sdk/flutter-sdk

**Comment by luvishq** [comment]
Awesome, will give it a try and connect with your team offline if this works for our usecase.
