### ISSUE TITLE
cannot run on flutter 3.3.10

### ISSUE THREAD

**Issue by abdullahwaheed12** [videosdk-live/videosdk-rtc-flutter-sdk-example#34]
i tried on every java verison 17,15,11,and 8 but still getting this error.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform audioswitch-c498d866c57f1d88056d5e7e7a78d622e3b0c046.aar (com.github.davidliu:audioswitch:c498d866c57f1d88056d5e7e7a78d622e3b0c046) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for AarResourcesCompilerTransform: C:\Users\abdullah\.gradle\caches\transforms-3\f81649683aef4eb6854f409a8444a1d1\transformed\jetified-audioswitch-c498d866c57f1d88056d5e7e7a78d622e3b0c046.
         > C:\Users\abdullah\.gradle\caches\transforms-3\f81649683aef4eb6854f409a8444a1d1\transformed\jetified-audioswitch-c498d866c57f1d88056d5e7e7a78d622e3b0c046\AndroidManifest.xml

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by rajansurani** [comment]
@abdullahwaheed12 Can you try running
```
rm -rf pubspec.lock
flutter clean
flutter pub get
```

And try running the app again.

**Comment by abdullahwaheed12** [comment]
> @abdullahwaheed12 Can you try running
> 
> ```
> rm -rf pubspec.lock
> flutter clean
> flutter pub get
> ```
> 
> And try running the app again.
 tried  rm -rf pubspec.lock and got this
Remove-Item : A parameter cannot be found that matches parameter name 'rf'.
At line:1 char:4
+ rm -rf pubspec.lock
+    ~~~
    + CategoryInfo          : InvalidArgument: (:) [Remove-Item], ParameterBindingException    
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.RemoveItemC 
   ommand

**Comment by rajansurani** [comment]
you can just manually remove the pubspec.lock file and then run the other commands

**Comment by abdullahwaheed12** [comment]
yes tried this thing but got same result

**Comment by rajansurani** [comment]
can you share the gradle version

**Comment by abdullahwaheed12** [comment]
i am runing this example and also used in my other project where i faced same issue
