### ISSUE TITLE
Not getting entryRequested

### ISSUE THREAD

**Issue by cg-sangam** [videosdk-live/videosdk-rtc-flutter-sdk-example#36]
When two or three user join calls at same time then i am not getting entry request and also when host joined the meeting instantly after creating group call then again join request not coming.

**Comment by rajansurani** [comment]
@cg-sangam Are you passing the `allow_join` and `allow_mod` permission in the host token and `ask_join` in the guest user's token?

**Comment by cg-sangam** [comment]
I added all permission still not able to get entry request .
Use case:-
When new room creates and host joined during creation of new room at that first time entry request not coming.
after host exit and join again same room at that time entry request comes.

**Comment by rajansurani** [comment]
@cg-sangam  can you share a video of your current implementation, where the case you mentioned is happening?

Also Please share code snippet where you have implemented the entryRequested and response.

**Comment by cg-sangam** [comment]
Sorry I fixed it actually the meetingId which  i am passing that is wrong at the time of new meeting creation
