### ISSUE TITLE
Can't run on iOS

### ISSUE THREAD

**Issue by jpcodr** [videosdk-live/videosdk-rtc-flutter-sdk-example#39]
I installed the videosdk package and now i can't run my app.

When i do `flutter run` throws:

```
Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences
```

I tried `flutter clean` and uninstall and reinstall the app with no success.

Am i missing something? If i remove the videosdk package everything works fine. Please help me.

Thanks

**Comment by rajansurani** [comment]
Please try downgrading the `shared_preferences` dependency to `2.0.15`
