### ISSUE TITLE
Compatibility issues with other packages that require http:1.1.0

### ISSUE THREAD

**Issue by arthurgichuhi** [videosdk-live/videosdk-rtc-flutter-sdk-example#45]
The videosdk flutter package is currently incompatible with the most other flutter packages since it uses http:0.13.5 while most packages require http:1.1.0 by default.
Below is the screenshot of the error I get when trying to retrieve packages.
![Screenshot from 2023-07-12 12-36-40](https://github.com/videosdk-live/videosdk-rtc-flutter-sdk-example/assets/86406883/7fc2ecac-e9df-48ef-86a4-08b2f052edd2)

**Comment by ishabodiwala** [comment]
hello @arthurgichuhi, Thank you for raising this issue. We will take this in our backlog and update you for the same.
