### ISSUE TITLE
No video stream - Camera not enabled

### ISSUE THREAD

**Issue by Consticonstantin** [videosdk-live/videosdk-rtc-flutter-sdk-example#49]
Hi all.
I've been trying to integrate the SDK into my existing app but could not get the video stream. I've also tried this example app but  it's  not working too. I figured out that the camera is not enabled. While trying to enable the camera, i get this error 

```
webrtc.Logging(22287): SurfaceTextureHelper: stopListening()
[log] Unable to RTCPeerConnection::createOffer: peerConnectionCreateOffer(): WEBRTC_CREATE_OFFER_ERROR: Session error code: ERROR_CONTENT. Session error description: Failed to set local video description recv parameters for m-section with mid='video'..
[log] #0      Transport._produce
      <asynchronous suspension>
#1      FlexQueue._runTask
      <asynchronous suspension>
```
![image](https://github.com/videosdk-live/videosdk-rtc-flutter-sdk-example/assets/22114983/e8b64a9d-d1ea-427a-a8dc-7b7f5408bf80)
 When i try to switch from/to front/back camera i get the output
`[log] camera is not enabled!`
Flutter doctor ouputs
```
[✓] Flutter (Channel stable, 3.10.0, on Pop!_OS 22.04 LTS 6.2.6-76060206-generic, locale fr_FR.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc2)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2022.3)
[✓] Connected device (3 available)
[✓] Network resources
```

Tested on Samsung T225N (Android 13), Pixel 4XL (Android 13)

**Comment by ishabodiwala** [comment]
Hey @Consticonstantin, are you facing this issue everyTime ?

**Comment by Consticonstantin** [comment]
Yes! Since couple of weeks

**Comment by ishabodiwala** [comment]
okay. Give us some to time to test it.

**Comment by ishabodiwala** [comment]
Hey @Consticonstantin, we are currently unable to replicate this issue. Our testing encompassed SM-M52 (operating on Android 13), as well as Pixel 4XL (Android 13 x86_64). Could you test on different devices and let us know the result ? It will helpful to address this issue.

**Comment by Consticonstantin** [comment]
I've tested on Redmi 7A  Android 10. Everything works well. Is there any reason this could happen?

**Comment by ishabodiwala** [comment]
Hey @Consticonstantin, Could you try following steps and let us know the result ? 

1. pass **false** to `micEnabled`, `camEnabled` parameter in `VideoSDK.createRoom()` method.
2. After joining the meeting, start Camera  through **toggleCamera** button.

**Comment by Consticonstantin** [comment]
I'm testing on a real device  Pixel 4XL android-arm64
When i pass false to micEnabled and camEnabled  i get this
`[log] camera is not enabled!`

**Comment by arjun-kava** [comment]
Hey, @Consticonstantin we are fixing this.

**Comment by ahmedbhesaniya97** [comment]
Hey @Consticonstantin,
Please schedule a call with us.
https://calendly.com/ahmed-207/videosdk-feedback-suggestions

**Comment by InvalidReferenceException** [comment]
same issue, needs urgent resolution

**Comment by ishabodiwala** [comment]
We couldn't reproduce the problem on our end, so we're closing this for now. If you encounter it again, please reopen with more details.
