### ISSUE TITLE
Blank dark screen

### ISSUE THREAD

**Issue by dev-justine** [videosdk-live/videosdk-rtc-flutter-sdk-example#5]
I started using this package last month for my project and it has been working fine. I was able to have video calls on my flutter app.

But, since yesterday, it hasn't been working. When, I try to have a video call, the screen just remains dark and blank, it doesn't even show my video.

I also tried the videosdk code example and it was the same thing.

This is my debug console log:

I/org.webrtc.Logging(17810): NativeLibrary: Loading native library: jingle_peerconnection_so
I/org.webrtc.Logging(17810): NativeLibrary: Loading library: jingle_peerconnection_so
W/.rimotli.avoca(17810): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
I/org.webrtc.Logging(17810): PeerConnectionFactory: PeerConnectionFactory was initialized without an injected Loggable. Any existing Loggable will be deleted.
I/org.webrtc.Logging(17810): EglBase14Impl: SDK version: 29. isEGL14Supported: true
I/org.webrtc.Logging(17810): EglBase14Impl: Using OpenGL ES version 2
I/org.webrtc.Logging(17810): WebRtcAudioManagerExternal: Sample rate is set to 48000 Hz
I/org.webrtc.Logging(17810): WebRtcAudioManagerExternal: Sample rate is set to 48000 Hz
E/org.webrtc.Logging(17810): JavaAudioDeviceModule: HW NS not supported
I/org.webrtc.Logging(17810): JavaAudioDeviceModule: createAudioDeviceModule
I/org.webrtc.Logging(17810): JavaAudioDeviceModule: HW NS will not be used.
I/org.webrtc.Logging(17810): JavaAudioDeviceModule: HW AEC will be used.
I/org.webrtc.Logging(17810): WebRtcAudioEffectsExternal: ctor@[name=main, id=2]
I/org.webrtc.Logging(17810): WebRtcAudioRecordExternal: ctor@[name=main, id=2]
I/org.webrtc.Logging(17810): WebRtcAudioTrackExternal: ctor@[name=main, id=2]
W/AudioCapabilities(17810): Unsupported mime audio/x-ima
W/AudioCapabilities(17810): Unsupported mime audio/mpeg-L1
W/AudioCapabilities(17810): Unsupported mime audio/mpeg-L2
W/AudioCapabilities(17810): Unsupported mime audio/x-ms-wma
W/VideoCapabilities(17810): Unsupported mime video/wvc1
W/VideoCapabilities(17810): Unsupported mime video/avc-wfd
W/VideoCapabilities(17810): Unsupported mime video/mp43
W/VideoCapabilities(17810): Unrecognized profile/level 1/32 for video/mp4v-es
W/VideoCapabilities(17810): Unrecognized profile/level 32768/2 for video/mp4v-es
W/VideoCapabilities(17810): Unrecognized profile/level 32768/64 for video/mp4v-es
W/VideoCapabilities(17810): Unsupported mime video/wvc1
W/VideoCapabilities(17810): Unsupported mime video/x-ms-wmv7
W/VideoCapabilities(17810): Unsupported mime video/x-ms-wmv8
I/org.webrtc.Logging(17810): WebRtcAudioRecordExternal: enableBuiltInAEC(true)
I/org.webrtc.Logging(17810): WebRtcAudioEffectsExternal: setAEC(true)
I/org.webrtc.Logging(17810): PeerConnectionFactory: onWorkerThreadReady
I/org.webrtc.Logging(17810): PeerConnectionFactory: onSignalingThreadReady
I/org.webrtc.Logging(17810): PeerConnectionFactory: onNetworkThreadReady
D/MediaConstraintsUtils(17810): mandatory constraints are not a map
I/FlutterWebRTCPlugin(17810): getUserMedia(audio): mandatory: [], optional: [sourceId: audio-1]
D/FlutterWebRTCPlugin(17810): MediaStream id: 78fae78f-de4f-4ebf-b8fb-6d9c97b5163b
W/.rimotli.avoca(17810): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed)
W/.rimotli.avoca(17810): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
W/.rimotli.avoca(17810): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
W/.rimotli.avoca(17810): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
W/.rimotli.avoca(17810): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed)
W/.rimotli.avoca(17810): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
W/.rimotli.avoca(17810): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed)
I/flutter (17810): request timeout
W/.rimotli.avoca(17810): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)

**Comment by yash-chudasama** [comment]
Hi @dev-justine, try to change permissions in Auth Server.

For Node.js Auth Server,

```
const payload = {
    apikey: API_KEY,
    permissions: ["allow_join"]
  };
```

**Comment by yash-chudasama** [comment]
Hii @dev-justine , I had faced same issue as yours, then I came to following solution. 

If above solution does not work, then you can go to [VideoSDK Dashboard](https://app.videosdk.live/dashboard) to check whether your account is activated or not.

If your account is deactivated, you can simply activate it by completing requested action.

**Comment by dev-justine** [comment]
Hi @yash-chudasama my account is active. I just checked it.

**Comment by dev-justine** [comment]
Ok, so i was able to reach out to the mod and it turns out, that my issue originated from my permissions on the node js server code.

i had added 3 permissions
```
  const payload = {
    apikey: API_KEY,
    permissions: ["allow_join", "allow_mod", "ask_join"],
  };
```

but i was meant to be just one, like @yash-chudasama mentioned

> Hi @dev-justine, try to change permissions in Auth Server.
> 
> For Node.js Auth Server,
> 
> ```
> const payload = {
>     apikey: API_KEY,
>     permissions: ["allow_join"]
>   };
> ```

**Comment by dev-justine** [comment]
This happened after an upgrade was made on their system
