### ISSUE TITLE
Audio output coming from earpiece

### ISSUE THREAD

**Issue by Sangam3798** [videosdk-live/videosdk-rtc-flutter-sdk-example#54]
after joining call by default audio is coming from earpiece not from speaker?

I joined a call and i am not connected to any other external audio output device and  every time i am getting audio from earpiece not  from speaker.

below is the sample code :   
 Room room = VideoSDK.createRoom(
      roomId: GroupSharingApi.instance.meetingId,
      token: GroupSharingApi.instance.videoSDKToken,
      displayName: '${_profile.firstName} ${_profile.lastName}',
      micEnabled: widget.micEnabled,
      camEnabled: widget.camEnabled,
      maxResolution: 'hd',
      multiStream: false,
      participantId: _userId,
      defaultCameraIndex: 1,
      notification: const NotificationInfo(
        title: "Video SDK",
        message: "Video SDK is sharing screen in the meeting",
        icon: "notification_share", // drawable icon name
      ),
    );

**Comment by ishabodiwala** [comment]
This issue is resolved in version `1.1.9`
