### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke interface method 'void org.webrtc.VideoCapturer.initialize(org.webrtc.SurfaceTextureHelper, android.content.Context, org.webrtc.CapturerObserver)' on a null object reference

### ISSUE THREAD

**Issue by sahil-ailoitte** [videosdk-live/videosdk-rtc-flutter-sdk-example#58]
java.lang.NullPointerException: Attempt to invoke interface method 'void org.webrtc.VideoCapturer.initialize(org.webrtc.SurfaceTextureHelper, android.content.Context, org.webrtc.CapturerObserver)' on a null object reference
E/AndroidRuntime(16634): 	at com.cloudwebrtc.webrtc.GetUserMediaImpl.getUserVideo(GetUserMediaImpl.java:761)
E/AndroidRuntime(16634): 	at com.cloudwebrtc.webrtc.GetUserMediaImpl.getUserMedia(GetUserMediaImpl.java:628)
E/AndroidRuntime(16634): 	at com.cloudwebrtc.webrtc.GetUserMediaImpl.access$100(GetUserMediaImpl.java:88)
E/AndroidRuntime(16634): 	at com.cloudwebrtc.webrtc.GetUserMediaImpl$2.invoke(GetUserMediaImpl.java:478)
E/AndroidRuntime(16634): 	at com.cloudwebrtc.webrtc.GetUserMediaImpl.lambda$requestPermissions$1(GetUserMediaImpl.java:880)
E/AndroidRuntime(16634): 	at com.cloudwebrtc.webrtc.GetUserMediaImpl$$ExternalSyntheticLambda0.invoke(Unknown Source:6)
E/AndroidRuntime(16634): 	at com.cloudwebrtc.webrtc.utils.PermissionUtils$1.onReceiveResult(PermissionUtils.java:115)
E/AndroidRuntime(16634): 	at android.os.ResultReceiver$MyRunnable.run(ResultReceiver.java:50)
E/AndroidRuntime(16634): 	at android.os.Handler.handleCallback(Handler.java:790)
E/AndroidRuntime(16634): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(16634): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(16634): 	at android.app.ActivityThread.main(ActivityThread.java:6977)
E/AndroidRuntime(16634): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(16634): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:528)
E/AndroidRuntime(16634): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:910)
I/Process (16634): Sending signal. PID: 16634 SIG: 9
Lost connection to device.

My app is getting crashed after calling join method on android 8. I have tested it on above versions it is working fine. I'm using   videosdk: ^1.1.10

**Comment by ishabodiwala** [comment]
We have resolved the issue. Please use the latest version of the SDK. If the problem persists, feel free to reopen the issue.
