### ISSUE TITLE
Please upgrade dependencies to latest version protobuf

### ISSUE THREAD

**Issue by Yoda-Man** [videosdk-live/videosdk-rtc-flutter-sdk-example#60]
Because barcode_scan2 >=4.3.0 depends on protobuf ^3.1.0 and every version of videosdk_otel depends on protobuf >=1.1.0 <3.0.0, barcode_scan2 >=4.3.0 is incompatible with
  videosdk_otel.
And because videosdk >=1.1.4 depends on videosdk_otel ^0.0.2, barcode_scan2 >=4.3.0 is incompatible with videosdk >=1.1.4.

**Comment by ishabodiwala** [comment]
Hello @Yoda-Man, we will upgrade the protobuf version soon, and let you know. Meanwhile, please override the dependency in your project.  Add the following lines in your `pubspec.yaml` file to do so.

dependency_overrides:
  protobuf: ">=3.1.0"
