### ISSUE TITLE
gradle 8+

### ISSUE THREAD

**Issue by Yoda-Man** [videosdk-live/videosdk-rtc-flutter-sdk-example#63]
A problem occurred configuring project ':videosdk'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file: /home/ind/.pub-cache/hosted/pub.dev/videosdk-1.1.12/android/build.gradle. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

     If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.

**Comment by danielesegato** [comment]
This is related to https://github.com/videosdk-live/videosdk-rtc-flutter-sdk-example/issues/67 I believe

**Comment by LakshayDCoder** [comment]
Any fixes for this issue?

**Comment by harshitbagga** [comment]
It seems like the namespace is incorrect Can you please check the namespace it should be same as the package name

**Comment by LakshayDCoder** [comment]
I added `namespace "live.videosdk.videosdk"` to the cache path `/Users/lg/.pub-cache/hosted/pub.dev/videosdk-1.2.3/android/build.gradle`

And that worked.

**Comment by halima1802** [comment]
Hi @Yoda-Man , it’s been a while since we last heard from you, so I'll go ahead and close this issue for now. If you’re still experiencing this problem or have any updates to share, please feel free to reopen it or create a new issue. Thanks for your understanding!

**Comment by Yoda-Man** [comment]
> I added `namespace "live.videosdk.videosdk"` to the cache path `/Users/lg/.pub-cache/hosted/pub.dev/videosdk-1.2.3/android/build.gradle`
> 
> And that worked.

Hi I have not tried this. I was still getting the same error after the latest update. I think it would be best if it just builds out of the box.

**Comment by Yoda-Man** [comment]
I will try you approach this weekend

**Comment by Suman2023** [comment]
Still getting the issue in videosdk-1.2.3

**Comment by Yoda-Man** [comment]
The work around worked
