### ISSUE TITLE
Keep dependencies up to date

### ISSUE THREAD

**Issue by danielesegato** [videosdk-live/videosdk-rtc-flutter-sdk-example#67]
Can you please release often keeping dependencies up to date?

I keep having issues with conflicting dependencies with your SDK and other libraries.

last of these is flutter_foreground_task that you require at version `6.1.3` while the last version is `8.8.1+1`

Not to be harsh but It makes your SDK undesirable in our codebase and therefore your service.

**Comment by halima1802** [comment]
Hey @danielesegato, We are extremely sorry for the inconvenience, We will surely keep this in mind and update all our dependencies as soon as possible!
