### ISSUE TITLE
Android emulator can't switch front and back camera.

### ISSUE THREAD

**Issue by snowdevman** [videosdk-live/videosdk-rtc-flutter-sdk-example#68]
getDevices function does not return the correct cameras. It returns two cameras with ids 0 and 1, but the back camera id is 10.
The facing mode is such kind of uncertain feature and makes confusing.
The code quality is pretty bad and hard to use it. Also, many bugs are in the sdk itself.
Not sure if the guys have tested the sample project.

**Comment by arjun-kava** [comment]
Please use real-device, some features are not compatible in emulator.

**Comment by snowdevman** [comment]
@arjun-kava Is there any feature to switch front and back camera of mobile devices?

**Comment by arjun-kava** [comment]
Yes, check this out: https://docs.videosdk.live/flutter/guide/video-and-audio-calling-api-sdk/handling-media/change-video-input-device

**Comment by halima1802** [comment]
Hi @snowdevman,

We apologize for any inconvenience you’ve experienced. We’d greatly appreciate it if you could share the specific bugs you encountered, as well as any parts of the example that felt challenging or unclear. Your feedback would be incredibly valuable in helping us improve the overall quality of the example and ensure a smoother experience for everyone.

Thank you so much for your help and understanding!

**Comment by halima1802** [comment]
Hi @snowdevman , it’s been a while since we last heard from you, so I'll go ahead and close this issue for now. If you’re still experiencing this problem or have any updates to share, please feel free to reopen it or create a new issue. Thanks for your understanding!
