### ISSUE TITLE
Android call volume issue

### ISSUE THREAD

**Issue by jowin-vincent-ailoitte** [videosdk-live/videosdk-rtc-flutter-sdk-example#70]
Call volume is not changing when using the physical buttons to change volume. Media volume is changing instead of call volume while using speaker and earpiece mode.

**Comment by harshitbagga** [comment]
Do you also encounter this issue when the speaker is set to the phone’s earpiece?

**Comment by jowin-vincent-ailoitte** [comment]
> Do you also encounter this issue when the speaker is set to the phone’s earpiece?

Yes, same issue in both speaker and earpiece mode.

**Comment by harshitbagga** [comment]
Hi,

Could we schedule a call? I’m unable to recreate the issue on my end and would like to check what exactly is going wrong.
You can book a meeting with me using this link:https://meetings.hubspot.com/harshit-bagga

**Comment by jowin-vincent-ailoitte** [comment]
I am not able to recreate the issue now. We opted to use a MethodChannel to listen for physical volume button taps to manage volume increase and decrease. Since then, a significant amount of code has changed. I will close this issue citing the same.
