### ISSUE TITLE
how to get video recording when video call finish

### ISSUE THREAD

**Issue by girishmobile** [videosdk-live/videosdk-rtc-flutter-sdk-example#75]
![Screenshot (162)](https://github.com/user-attachments/assets/b76fcbcf-71ea-4b80-b5da-2e5e21f2079c)
i am try to get recording text file, audio via api then facing issue like token is not valid,

**Comment by ishabodiwala** [comment]
Hey @girishmobile, If you're facing the same error, please reach out to us here: https://www.videosdk.live/contact. Thank you.
