### ISSUE TITLE
Incompatible with Flutter 3.27.0, please update dependencies

### ISSUE THREAD

**Issue by booooohdan** [videosdk-live/videosdk-rtc-flutter-sdk-example#79]
Incompatible with Flutter 3.27.0, please update dependencies

**Comment by booooohdan** [comment]
Any updates? Guys, we paid for this

**Comment by arjun-kava** [comment]
Hey, @booooohdan. We will pick this soon. To understand issue further, please connect to us here: https://www.videosdk.live/contact
Thanks.

**Comment by halima1802** [comment]
Hey @booooohdan @M3hdi , We've updated our internal dependencies and resolved compatibility issues with Flutter 3.27. Please update the SDK to version 1.2.5.
Thank you! If you need any further assistance, don't hesitate to reach out.

**Comment by booooohdan** [comment]
It works. Thank you
