### ISSUE TITLE
.env file not found

### ISSUE THREAD

**Issue by pragneshpalsana1999** [videosdk-live/videosdk-rtc-flutter-sdk-example#8]
flutter:
Error: unable to find directory entry in pubspec.yaml: C:\Users\pprag\Downloads\azaz\.env\

**Comment by yash-chudasama** [comment]
Hi @pragneshpalsana1999, Please read README.md file.

Copy .env.example file to .env file
And
Either update AUTH_TOKEN or AUTH_URL in the .env file.
